
export const INGREDIENTS = [
    'garlic',
    'tomato',
    'parmesan',
    'beef',
    'onion',
    'spaghetti',
    'celery',
    'carrot',
    'bacon',
    'lasagne sheets',
    'honey',
    'chocolate',
    'mars bar ',
    'rice krispies',
    'eggs',
    'butter',
    'parsley',
    'chives',
    'mozzarella',
    'flour',
    'apple',
    'cinnamon',
    'egg',
    'chicken',
    'pepper',
    'beans',
    'quinoa',
    'corn',
    'lamb',
    'ginger',
    'chilli',
    'anise',
    'lime',
    'mint',
    'potato',
    'noodle',
    'cucumber',
    'radish',
    'sugar',
    'baguette',
    'lettuce',
    'kale',
    'soy sauce',
    'oyster sauce',
    'cumin',
    'chicken wings',
    'vinegar',
    'peper',
    'olives',
    'paprika',
    'almond',
    'yogurt',
    'beetroot',
    'mustard',
    'curry',
    'bread',
    'worcestershire sauce',
    'bourbon',
    'cabbage',
    'cheese',
    'tortilla',
    'peach',
    'feta',
    'ciabatta',
    'radishes',
    'pollock'

];
