export const IMAGES_SRC = [
    { name: 'garlic', src: '../../../assets/images/food-images/garlic.png'},
    { name: 'tomato', src: '../../../assets/images/food-images/tomato.png'},
    { name: 'beef', src: '../../../assets/images/food-images/beef.png'},
    { name: 'onion', src: '../../../assets/images/food-images/onion.png'},
    { name: 'spaghetti', src: '../../../assets/images/food-images/spaghetti.png'},
    { name: 'celery', src: '../../../assets/images/food-images/celery.png'},
    { name: 'carrot', src: '../../../assets/images/food-images/carrot.png'},
    { name: 'bacon', src: '../../../assets/images/food-images/bacon.png'},
    { name: 'lasagne sheets', src: '../../../assets/images/food-images/lasagne sheets.png'},
    { name: 'honey', src: '../../../assets/images/food-images/honey.png'},
    { name: 'chocolate', src: '../../../assets/images/food-images/chocolate.png'},
    { name: 'rice krispies', src: '../../../assets/images/food-images/rice krispies.png'},
    { name: 'eggs', src: '../../../assets/images/food-images/eggs.png'},
    { name: 'butter', src: '../../../assets/images/food-images/butter.png'},
    { name: 'parsley', src: '../../../assets/images/food-images/parsley.png'},
    { name: 'chives', src: '../../../assets/images/food-images/chives.png'},
    { name: 'flour', src: '../../../assets/images/food-images/flour.png'},
    { name: 'apple', src: '../../../assets/images/food-images/apple.png'},
    { name: 'cinnamon', src: '../../../assets/images/food-images/cinnamon.png'},
    { name: 'chicken', src: '../../../assets/images/food-images/chicken.png'},
    { name: 'beans', src: '../../../assets/images/food-images/beans.png'},
    { name: 'corn', src: '../../../assets/images/food-images/corn.png'},
    { name: 'lamb', src: '../../../assets/images/food-images/lamb.png'},
    { name: 'ginger', src: '../../../assets/images/food-images/ginger.png'},
    { name: 'chilli', src: '../../../assets/images/food-images/chilli.png'},
    { name: 'anise', src: '../../../assets/images/food-images/anise.png'},
    { name: 'lime', src: '../../../assets/images/food-images/lime.png'},
    { name: 'potato', src: '../../../assets/images/food-images/potato.png'},
    { name: 'noodle', src: '../../../assets/images/food-images/noodle.png'},
    { name: 'cucumber', src: '../../../assets/images/food-images/cucumber.png'},
    { name: 'radish', src: '../../../assets/images/food-images/radish.png'},
    { name: 'baguette', src: '../../../assets/images/food-images/baguette.png'},
    { name: 'lettuce', src: '../../../assets/images/food-images/lettuce.png'},
    { name: 'kale', src: '../../../assets/images/food-images/kale.png'},
    { name: 'vinegar', src: '../../../assets/images/food-images/vinegar.png'},
    { name: 'olives', src: '../../../assets/images/food-images/olives.png'},
    { name: 'paprika', src: '../../../assets/images/food-images/paprika.png'},
    { name: 'almond', src: '../../../assets/images/food-images/almond.png'},
    { name: 'yogurt', src: '../../../assets/images/food-images/yogurt.png'},
    { name: 'beetroot', src: '../../../assets/images/food-images/beetroot.png'},
    { name: 'cabbage', src: '../../../assets/images/food-images/cabbage.png'},
    { name: 'cheese', src: '../../../assets/images/food-images/cheese.png'},
    { name: 'tortilla', src: '../../../assets/images/food-images/tortilla.png'},
    { name: 'peach', src: '../../../assets/images/food-images/peach.png'},
    { name: 'bourbon', src: '../../../assets/images/food-images/bourbon.png'},
    { name: 'bread', src: '../../../assets/images/food-images/bread.png'},
    { name: 'chicken wings', src: '../../../assets/images/food-images/chicken wings.png'},
    { name: 'ciabatta', src: '../../../assets/images/food-images/ciabatta.png'},
    { name: 'cumin', src: '../../../assets/images/food-images/cumin.png'},
    { name: 'curry', src: '../../../assets/images/food-images/curry.png'},
    { name: 'feta', src: '../../../assets/images/food-images/feta.png'},
    { name: 'fish', src: '../../../assets/images/food-images/fish.png'},
    { name: 'ketchup', src: '../../../assets/images/food-images/ketchup.png'},
    { name: 'lemon', src: '../../../assets/images/food-images/lemon.png'},
    { name: 'mars bar', src: '../../../assets/images/food-images/mars bar.png'},
    { name: 'mint', src: '../../../assets/images/food-images/mint.png'},
    { name: 'mozzarella', src: '../../../assets/images/food-images/mozzarella.png'},
    { name: 'olive oil', src: '../../../assets/images/food-images/olive oil.png'},
    { name: 'oyster sauce', src: '../../../assets/images/food-images/oyster sauce.png'},
    { name: 'parmesan', src: '../../../assets/images/food-images/parmesan.png'},
    { name: 'peas', src: '../../../assets/images/food-images/peas.png'},
    { name: 'pepper', src: '../../../assets/images/food-images/pepper.png'},
    { name: 'pollock', src: '../../../assets/images/food-images/pollock.png'},
    { name: 'quinoa', src: '../../../assets/images/food-images/quinoa.png'},
    { name: 'soy sauce', src: '../../../assets/images/food-images/soy sauce.png'},
    { name: 'sugar', src: '../../../assets/images/food-images/sugar.png'},
    { name: 'sunflower oil', src: '../../../assets/images/food-images/sunflower oil.png'},
    { name: 'worcestershire sauce', src: '../../../assets/images/food-images/worcestershire sauce.png'},
    { name: 'paprica', src: '../../../assets/images/food-images/paprica.png'},
    { name: 'mustard', src: '../../../assets/images/food-images/mustard.png'},

];
